name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
      
    - name: Configure
      working-directory: src-cpp
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
    
    - name: Build
      working-directory: src-cpp/build
      run: cmake --build . --config Release
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: triga-editor
        path: src-cpp/build/bin/
